export type RootStackParamList = {
  Home: undefined;
  Login: undefined;
  Register: undefined;
  ResetPassword: undefined;
  UserProfile: undefined;
  EditProfile: undefined;
  Settings: undefined;
  List: undefined;
  AddOrder: undefined;
  Detail: undefined;
  Search: undefined;
  Notifications: undefined;
  Form: undefined;
  Payment: undefined;
  Success: undefined;
  OrderHistory: undefined;
  HelpSupport: undefined;
  TransactionDetails: { transactionId: string };
  AdminPanel: undefined;
  Main: undefined;
  ItemDetails: { orderId: number };
  CurrentLocation: undefined;
  AssignedOrders: undefined;
  Raport: { orderId: number };
  AddRaport: { orderId: number; guardId: number };
  UserRaports: undefined;
};
