export type RootStackParamList = {
  Home: undefined;
  Login: undefined;
  Register: undefined;
  ResetPassword: undefined;
  UserProfile: undefined;
  EditProfile: undefined;
  Settings: undefined;
  List: undefined;
  Detail: undefined;
  Search: undefined;
  Notifications: undefined;
  Form: undefined;
  Payment: undefined;
  Success: undefined;
  OrderHistory: undefined;
  HelpSupport: undefined;
  TransactionDetails: undefined;
  Main: undefined;
    ItemDetails: { itemId: number };
};
