export type RootStackParamList = {
  Home: undefined;
  Login: undefined;
  Register: undefined;
  ResetPassword: undefined;
  UserProfile: undefined;
  Settings: undefined;
  List: undefined;
  Detail: undefined;
  Search: undefined;
  Notifications: undefined;
  Form: undefined;
  Payment: undefined;
  TransactionDetails: { transactionId: string };
  Error: { message?: string };
  Success: undefined;
  OrderHistory: undefined;
  HelpSupport: undefined;
  Main: undefined;
};
